# hw2_system.py
# Homework 2: AI Agent System with RAG and Tools — Main Entry Point
# Danny Atik - SYSEN 5381
#
# This is the main system file that ties together all components:
#   - rag.py         → RAG search function (search_startups)
#   - tools.py       → Tool functions (fetch_stock_data, compute_performance_metrics,
#                       get_latest_price)
#   - agents.py      → Multi-agent orchestration (4-agent pipeline)
#   - functions.py   → Shared LLM agent helpers (agent_run)
#   - startups.csv   → RAG data source (100 tech startups)
#   - 01_ollama.py   → Ollama server launcher
#
# All files are in this directory — no external dependencies.
#
# Run: python hw2_system.py

# 0. SETUP ###################################

import sys
import os
import json
from pathlib import Path
from dotenv import load_dotenv

## Working Directory — everything is in the HW2 folder
script_dir = Path(__file__).resolve().parent
os.chdir(script_dir)

## Load Environment Variables
load_dotenv(script_dir / ".env")
load_dotenv(script_dir.parent.parent / ".env")  # fallback to project root

MASSIVE_API_KEY = os.getenv("MASSIVE_API_KEY")
if not MASSIVE_API_KEY:
    raise ValueError("MASSIVE_API_KEY not found in .env. Please set it up first.")

## Start Ollama Server
import runpy
_ = runpy.run_path(os.path.join(os.getcwd(), "01_ollama.py"))

## Load shared agent functions (local copy)
sys.path.insert(0, os.getcwd())
from functions import agent_run
import functions as _fn

## Import HW2 modules (all local)
from rag import search_startups                              # RAG tool
from tools import fetch_stock_data                           # API tool 1
from tools import compute_performance_metrics                # Computation tool 2
from tools import get_latest_price                           # API tool 3
from agents import run_pipeline                              # Multi-agent orchestration

## Register tool functions in the functions module for the agent wrapper
_fn.search_startups = search_startups
_fn.fetch_stock_data = fetch_stock_data
_fn.compute_performance_metrics = compute_performance_metrics
_fn.get_latest_price = get_latest_price

## Configuration
MODEL = "smollm2:1.7b"
STARTUP_CSV = script_dir / "startups.csv"
INDUSTRY_QUERY = "AI"


# 1. RUN PIPELINE ###################################

print("=" * 70)
print("🧠 AI AGENT SYSTEM: Startup Market Intelligence Pipeline")
print("=" * 70)
print()
print(f"   Industry Query: {INDUSTRY_QUERY}")
print()

results = run_pipeline(
    industry_query=INDUSTRY_QUERY,
    agent_run_fn=agent_run,
    search_fn=search_startups,
    fetch_fn=fetch_stock_data,
    compute_fn=compute_performance_metrics,
    latest_fn=get_latest_price,
    api_key=MASSIVE_API_KEY,
    csv_path=str(STARTUP_CSV),
    model=MODEL,
)


# 2. SAVE REPORT ###################################

report_path = script_dir / "hw2_report.md"
tickers = results["comparable_tickers"]
startups = results["startups"]
performance_data = results["performance_data"]
latest_prices = results["latest_prices"]
analysis = results["analysis"]

md_content = f"""# Investment Analysis: {INDUSTRY_QUERY} Sector

*Generated by HW2 AI Agent System — Multi-Agent Pipeline*
*Comparable tickers analyzed: {', '.join(tickers)}*

---

## Pipeline Summary

| Agent | Role | Method | Output |
|-------|------|--------|--------|
| Agent 1 | Research Analyst | RAG (CSV search) | {len(startups)} startups found |
| Agent 2 | Market Mapper | LLM inference | Comparable tickers: {', '.join(tickers)} |
| Agent 3 | Data Engineer | 3 tools (API + compute) | 3-year metrics + latest prices |
| Agent 4 | Investment Advisor | LLM synthesis | Investment analysis report |

---

## Agent 3 Output: Comparable Ticker Performance

"""

for p in performance_data:
    if "error" not in p:
        # Find matching latest price
        lp = next((l for l in latest_prices if l.get("ticker") == p["ticker"]), {})
        latest_close = lp.get("previous_close", "N/A")
        md_content += f"""### {p['ticker']}
- **Period**: {p.get('period', 'N/A')}
- **Total Return**: {p.get('total_return_pct', '?')}%
- **Annualized Return**: {p.get('annualized_return_pct', '?')}%
- **Volatility**: {p.get('annualized_volatility_pct', '?')}%
- **3-Year Range**: ${p.get('3_year_low', '?')} — ${p.get('3_year_high', '?')}
- **Latest Close**: ${latest_close}
- **EMA Trend**: ${p.get('ema_2q', '?')} ({p.get('trend', '?')})

"""
    else:
        md_content += f"""### {p['ticker']}
- Error: {p.get('error')}

"""

md_content += f"""---

## Agent 4 Output: Investment Analysis

{analysis}
"""

with open(report_path, "w", encoding="utf-8") as f:
    f.write(md_content)


# 3. WORKFLOW SUMMARY ###################################

print("=" * 70)
print("✅ WORKFLOW COMPLETE")
print("=" * 70)
print()
print("Pipeline:")
print(f"  Agent 1 (RAG)       → Searched startups for '{INDUSTRY_QUERY}': {len(startups)} matches")
print(f"  Agent 2 (LLM)       → Identified comparables: {', '.join(tickers)}")
print(f"  Agent 3 (Tools)     → fetch_stock_data + compute_metrics + get_latest_price")
print(f"  Agent 4 (Synthesis)  → Generated investment analysis")
print()
print(f"📄 Report saved to: {report_path}")
